---
language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - check
  homebrew:
    packages:
      - check
    update: true

before_script:
  - sh autogen.sh

script:
  - ./configure
  - make
  - make check
